<a href="https://colab.research.google.com/github/Swayamswapnila/Python/blob/master/python_py.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
5+5

10

In [ ]:
print("1. addition")
print("2.substaction")
print("3.multiplication")
print("4.division")
print("5.foe power")

while 5==5:
 A = int(input("enter a numer"))
 B = int(input("entre a number"))
 choose = int(input("Enter choice (1/2/3/4/5): "))
 if choose == 1:
  c = A+B
  print(c)
 elif choose == 2:
  c = A-B
  print(c)
 elif choose == 3:
  c = A*B
  print(c)
 elif choose == 4:
  c = A/B
  print(c)
 elif choose == 5:
  c =A**B
  print(c)
 else:
  print("invalid input")
 Z = input("Let's do next calculation? (yes/no): ")
 if Z =="yes":
  continue
 elif Z =="no":
  break
 else:
  print("invalid")
  break

1. addition
2.substaction
3.multiplication
4.division
5.foe power
enter a numer10
entre a number20
Enter choice (1/2/3/4/5): 5
100000000000000000000
Let's do next calculation? (yes/no): yes
enter a numer2
entre a number12
Enter choice (1/2/3/4/5): 1
14
Let's do next calculation? (yes/no): n
invalid


In [ ]:
# This function adds two numbers
def add(x, y):
    return x + y

# This function subtracts two numbers
def subtract(x, y):
    return x - y

# This function multiplies two numbers
def multiply(x, y):
    return x * y

# This function divides two numbers
def divide(x, y):
    return x / y

print("Select operation.")
print("1.Add")
print("2.Subtract")
print("3.Multiply")
print("4.Divide")

while True:
    # take input from the user
    choice = input("Enter choice (1/2/3/4): ")

    # check if choice is one of the four options
    if choice in ('1', '2', '3', '4'):
        try:
            num1 = float(input("Enter first number: "))
            num2 = float(input("Enter second number: "))
        except ValueError:
            print("Invalid input. Please enter a number.")
            continue

        if choice == '1':
            print(num1, "+", num2, "=", add(num1, num2))

        elif choice == '2':
            print(num1, "-", num2, "=", subtract(num1, num2))

        elif choice == '3':
            print(num1, "*", num2, "=", multiply(num1, num2))

        elif choice == '4':
            print(num1, "/", num2, "=", divide(num1, num2))

        # check if user wants another calculation
        # break the while loop if answer is no
        next_calculation = input("Let's do next calculation? (yes/no): ")
        if next_calculation == "no":
            break

    else:
        print("Invalid Input")


Select operation.
1.Add
2.Subtract
3.Multiply
4.Divide
Enter choice (1/2/3/4): 1
Enter first number: 10
Enter second number: 5
10.0 + 5.0 = 15.0
Let's do next calculation? (yes/no): yes
Enter choice (1/2/3/4): 4544
Invalid Input
Enter choice (1/2/3/4): 1
Enter first number: 4214
Enter second number: 555
4214.0 + 555.0 = 4769.0
Let's do next calculation? (yes/no): no


In [ ]:
A = list((5,4,2,5))
print(A)
print(type(A))

In [ ]:
A = 10
while A>0:
  A-=1
  if(A!=5):
    print(A)
  else:
    break

In [ ]:
A = 10
while A>0:
  A-=1
  if(A!=5):
    print(A)
  else:
    continue

In [ ]:
def multiply(A,B):
    multiply = A*B
    return multiply



In [ ]:
#"for get binary of any number"
A = bin(int(input()))
print(A)
print(type(A))

2
0b10
<class 'str'>


In [ ]:
A = list(set((2,5,8,4)))
print(A)
print(type(A))

[8, 2, 4, 5]
<class 'list'>


In [ ]:
#"for calculate factorial"
N = int(input())
for i in range(1,N):
  N = N*i
print(N)

5
120


In [ ]:
import numpy as np
L = [1,2,5,8,9,3]
A = np.array(L)
print(A)
print(type(A))

[1 2 5 8 9 3]
<class 'numpy.ndarray'>


In [ ]:
import numpy as np
A = np.arange(7)
print(A)

[0 1 2 3 4 5 6]


In [ ]:
import numpy as np
A = np.linspace(2,20,10)
print(A)

[ 2.  4.  6.  8. 10. 12. 14. 16. 18. 20.]


In [ ]:
# for find factors of a number
L = list()
A = int(input())
for a in range(1,A):
  if A%a == 0:
    L.append(a)
print(L)

100
[1, 2, 4, 5, 10, 20, 25, 50]


In [ ]:
#find fabonacci series
A =[0,1]
N = int(input())
for i in range (N):
  S = A[i+1]+A[i]
  A.append(S)
print(A)

10
[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89]


In [ ]:
#for find AP by numpy
import numpy as np
A = int(input("first term ="))
B = int(input("last term ="))
C = int(input("no.of terms = "))
AP = np.linspace(A,B,C)
print(AP)

In [ ]:
# Import the datetime module
import datetime

# Define a function to calculate the age
def calculate_age(dob, today):
  # Check if the date of birth is valid
  if dob > today:
    return "Invalid date of birth"
  # Calculate the year difference
  years = today.year - dob.year
  # Adjust the year difference if the birthday has not passed yet
  if (today.month, today.day) < (dob.month, dob.day):
    years -= 1
  # Calculate the month difference
  months = today.month - dob.month
  # Adjust the month difference if the day of the month has not passed yet
  if today.day < dob.day:
    months -= 1
  # Calculate the day difference
  days = today.day - dob.day
  # Adjust the day difference if the month has changed
  if days < 0:
    # Get the number of days in the previous month
    prev_month = today.replace(day=1) - datetime.timedelta(days=1)
    days_in_month = prev_month.day
    # Add the days in the previous month to the day difference
    days += days_in_month
  # Return the age as a string
  return f"{years} years, {months} months and {days} days"

# Get the current date
today = datetime.date.today()
# Get the date of birth from the user input
dob = datetime.date(int(input("Enter your birth year: ")), int(input("Enter your birth month: ")), int(input("Enter your birth day: ")))
# Call the function and print the result
print("Your age is:", calculate_age(dob, today))


Enter your birth year: 2007
Enter your birth month: 3
Enter your birth day: 7
Your age is: 16 years, 8 months and 21 days


In [6]:
def is_palindrome(s):
    return s == s[::-1]

string = input()
if is_palindrome(string):
    print(f"{string} is a palindrome.")
else:
    print(f"{string} is not a palindrome.")


1231
1231 is not a palindrome.


In [9]:
string = input("Enter a string: ")
i = 0
j = len(string) - 1

while i < j:
    if string[i] != string[j]:
        print(f"{string} is not a palindrome.")
        break
    i += 1
    j -= 1
else:
    print(f"{string} is a palindrome.")

Enter a string: 12321
12321 is a palindrome.
